title: "Skip's Portfolio Website"
description: "My personal site to display my projects and interests. Besides coding, I’m an avid hang-glider, skier and mopuntain biker located at the southern end of the Rockies in Santa Fe, NM."
url: "https://skipmcgee.github.io"
baseurl: ""

author: "Skip McGee"
social:
  name: "Skip McGee"
  links:
    - "https://linkedin.com/in/skip-mcgee"
    - "https://github.com/skipmcgee"
google_analytics: "G-TXJDG6Q5E2"