title: "Skip McGee - Cybersecurity Engineer & Computer Scientist"
description: "Cybersecurity Engineer and Computer Scientist with a variety of interests: application development, scripting, SIEM, threat hunting, networking, vulnerability scanning and device hardening."
url: "https://skipmcgee.github.io"
baseurl: ""
image: "/assets/img/profile.jpg"

author: "Skip McGee"
social:
  name: "Skip McGee"
  links:
    - "https://linkedin.com/in/skip-mcgee"
    - "https://github.com/skipmcgee"
google_analytics: "G-TXJDG6Q5E2"