theme : jekyll-theme-slate
title : [Welcome to Skip McGee's page: ]
description: [a personal introduction to my code and projects]

author :
  name : [Skip McGee]
  email : [davidfranklinmcgee@gmail.com]
  github : [skipmcgee]
production_url : [https://skipmcgee.github.io]
navbar-links :
  About Me : [Learning and improving coding skills]
  Resources :
  - README: "README.md"
  - Code Fellows: "https://skipmcgee.github.io/reading-notes/"
include : 
  - README.md
plugins :
  - jekyll-paginate
  - jekyll-sitemap
JB :
  BASE_PATH : https://skipmcgee.github.io/
pages :
  markdown :
    extra : true
    
#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# --- Web Analytics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "G-TXJDG6Q5E2"

# Fill in your Google Analytics ID to track your website using Google Analytics
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""
